import type { Level3TopicSpec } from './factory';

export const level3TopicSpecs: Level3TopicSpec[] = [
  {
    id: 'ethics',
    title: 'Ethics & Professional Standards',
    examWeight: '10-15%',
    pathway: 'core',
    focus: 'portfolio-manager conduct, conflicts, suitability, supervision, and professional judgment',
    caseFrames: ['A portfolio manager reviews a discretionary mandate after a side arrangement is disclosed', 'A compliance officer evaluates whether client reporting and trade allocation are supportable'],
    decisions: ['select the conduct response supported by the mandate', 'evaluate the disclosure or supervisory step required', 'justify the client-first action when interests conflict', 'determine whether the report is fair and complete'],
    traps: ['treating disclosure as a substitute for fair dealing', 'assuming client sophistication cures an unsupported action', 'using firm approval without documenting the client impact'],
    commandWords: ['determine', 'justify', 'recommend', 'evaluate', 'identify', 'explain'],
    formulas: ['Client-first decision check', 'Conflict disclosure sufficiency', 'Fair presentation screen', 'Supervisory escalation path', 'Suitability constraint bridge', 'Allocation fairness test'],
    datasetRows: [
      { case: 'allocation review', mandate: 'balanced income', conflict: 'limited opportunity', evidence: 'documented policy' },
      { case: 'side arrangement', mandate: 'growth portfolio', conflict: 'issuer access', evidence: 'committee minutes' },
      { case: 'report revision', mandate: 'foundation reserve', conflict: 'performance claim', evidence: 'corrected exhibit' },
    ],
  },
  {
    id: 'asset-allocation',
    title: 'Asset Allocation',
    examWeight: '15-20%',
    pathway: 'core',
    focus: 'capital market expectations, strategic allocation, tactical tilts, rebalancing, and constraint-aware policy design',
    caseFrames: ['An investment committee revisits policy weights after return expectations and liabilities change', 'A strategist evaluates a tactical tilt while preserving risk and liquidity constraints'],
    decisions: ['recommend the policy allocation response', 'justify a rebalancing band or trigger', 'evaluate whether a tactical tilt is consistent with the mandate', 'determine the risk trade-off created by revised expectations'],
    traps: ['optimizing on expected return while ignoring liquidity needs', 'treating a tactical view as a permanent policy change', 'using stale volatility estimates after a regime shift'],
    commandWords: ['recommend', 'justify', 'determine', 'evaluate', 'calculate', 'explain'],
    formulas: ['Policy weight drift', 'Rebalancing tolerance band', 'Liquidity reserve coverage', 'Expected portfolio risk bridge', 'Tactical active-risk budget', 'Capital market assumption check'],
    datasetRows: [
      { portfolio: 'Reserve fund', targetEquity: '42%', actualEquity: '49%', liquidityNeed: '8 months' },
      { portfolio: 'Growth pool', targetEquity: '68%', actualEquity: '63%', liquidityNeed: 'low' },
      { portfolio: 'Liability pool', targetEquity: '28%', actualEquity: '31%', liquidityNeed: 'quarterly' },
    ],
  },
  {
    id: 'portfolio-construction',
    title: 'Portfolio Construction',
    examWeight: '15-20%',
    pathway: 'core',
    focus: 'risk budgets, active risk, manager selection, implementation choices, and portfolio design',
    caseFrames: ['A committee compares manager lineups after active risk and fee budgets are revised', 'A portfolio team evaluates whether implementation choices still match client constraints'],
    decisions: ['evaluate the manager or sleeve that best fits the risk budget', 'recommend an implementation change supported by the case facts', 'determine whether active risk is being used efficiently', 'justify a portfolio design adjustment'],
    traps: ['choosing the highest alpha without checking tracking error', 'treating low fees as proof of better implementation', 'adding managers without measuring overlapping exposures'],
    commandWords: ['evaluate', 'recommend', 'determine', 'justify', 'compare', 'explain'],
    formulas: ['Active risk contribution', 'Information ratio screen', 'Manager overlap check', 'Implementation shortfall bridge', 'Fee-adjusted active return', 'Risk budget use'],
    datasetRows: [
      { manager: 'Aster Active', activeReturn: '1.4%', trackingError: '3.2%', fee: '55 bp' },
      { manager: 'Beacon Core', activeReturn: '0.8%', trackingError: '1.4%', fee: '18 bp' },
      { manager: 'Cobalt Tilt', activeReturn: '1.9%', trackingError: '5.1%', fee: '42 bp' },
    ],
  },
  {
    id: 'performance',
    title: 'Performance Measurement',
    examWeight: '5-10%',
    pathway: 'core',
    focus: 'benchmark quality, attribution, appraisal, manager monitoring, and performance communication',
    caseFrames: ['A sponsor reviews attribution after a portfolio beat an unsuitable benchmark', 'An oversight group evaluates manager skill after risk and cash-flow effects are separated'],
    decisions: ['determine whether the benchmark is appropriate', 'evaluate the attribution evidence supporting skill', 'justify a monitoring action after a performance review', 'recommend a reporting adjustment for clearer communication'],
    traps: ['crediting active skill when benchmark choice explains the result', 'ignoring cash flows when interpreting returns', 'using total return without measuring risk taken'],
    commandWords: ['determine', 'evaluate', 'justify', 'recommend', 'calculate', 'explain'],
    formulas: ['Benchmark fit screen', 'Selection effect bridge', 'Allocation effect bridge', 'Risk-adjusted appraisal check', 'Cash-flow timing screen', 'Manager monitoring trigger'],
    datasetRows: [
      { portfolio: 'Global equity', return: '8.4%', benchmark: 'domestic equity', activeRisk: '6.1%' },
      { portfolio: 'Income sleeve', return: '4.1%', benchmark: 'aggregate bond', activeRisk: '1.2%' },
      { portfolio: 'Balanced pool', return: '6.7%', benchmark: 'policy blend', activeRisk: '2.4%' },
    ],
  },
  {
    id: 'derivatives-risk',
    title: 'Derivatives And Risk Management',
    examWeight: '10-15%',
    pathway: 'core',
    focus: 'overlay strategies, option structures, currency risk, hedge evaluation, and risk-control decisions',
    caseFrames: ['A risk team evaluates overlay alternatives after currency and equity exposures move away from policy', 'A treasury group reviews option protection after volatility and funding constraints change'],
    decisions: ['recommend the hedge that best offsets the exposure', 'evaluate whether the option structure fits the risk objective', 'determine the residual risk after the overlay', 'justify a risk-control action from the case facts'],
    traps: ['hedging in the same direction as the exposure', 'ignoring option cost when protection is budget constrained', 'treating notional amount as the same as risk reduction'],
    commandWords: ['recommend', 'evaluate', 'determine', 'justify', 'calculate', 'explain'],
    formulas: ['Hedge ratio check', 'Option collar payoff', 'Currency overlay exposure', 'Residual risk bridge', 'Protection cost screen', 'Derivative notional alignment'],
    datasetRows: [
      { exposure: 'foreign equity', notional: 180, hedge: 'forward sale', budget: 'limited' },
      { exposure: 'equity drawdown', notional: 240, hedge: 'put spread', budget: 'premium cap' },
      { exposure: 'rate liability', notional: 320, hedge: 'payer swaption', budget: 'moderate' },
    ],
  },
  {
    id: 'pm-pathway',
    title: 'Portfolio Management Pathway',
    examWeight: '30-35%',
    pathway: 'portfolio-management',
    focus: 'active equity, fixed-income strategy, index design, risk budgeting, and portfolio implementation',
    caseFrames: ['A pathway committee integrates equity, fixed-income, and index-design evidence into one implementation plan', 'A CIO reviews multi-asset portfolio changes after risk, cost, and liquidity constraints shift'],
    decisions: ['recommend the integrated portfolio action', 'justify the implementation path across asset-class sleeves', 'evaluate whether the pathway choice respects risk and liquidity limits', 'determine the monitoring metric that best controls the plan'],
    traps: ['solving each sleeve independently while ignoring total portfolio risk', 'choosing the lowest-cost implementation without matching exposure needs', 'adding active bets after the risk budget is already exhausted'],
    commandWords: ['recommend', 'justify', 'evaluate', 'determine', 'compare', 'explain'],
    formulas: ['Total active-risk budget', 'Fixed-income duration target', 'Equity factor exposure check', 'Index replication trade-off', 'Liquidity-adjusted implementation cost', 'Multi-sleeve monitoring trigger'],
    datasetRows: [
      { sleeve: 'active equity', activeRisk: '3.8%', liquidity: 'daily', cost: '52 bp' },
      { sleeve: 'liability fixed income', activeRisk: '1.1%', liquidity: 'weekly', cost: '18 bp' },
      { sleeve: 'custom index', activeRisk: '0.6%', liquidity: 'daily', cost: '8 bp' },
    ],
  },
  {
    id: 'private-markets-pathway',
    title: 'Private Markets Pathway',
    examWeight: '30-35%',
    pathway: 'private-markets',
    focus: 'private equity, private credit, real assets, infrastructure, fund structures, fees, valuation, and GP/LP decisions',
    caseFrames: ['An investment committee reviews a private markets allocation after liquidity and fee constraints tighten', 'A general partner evaluates capital structure, valuation, and exit alternatives for a portfolio company'],
    decisions: ['recommend the private markets allocation response', 'evaluate whether the fund structure fits the investor constraint', 'justify the valuation or financing assumption from the case facts', 'determine the monitoring metric that protects the limited partner'],
    traps: ['treating appraisal marks as traded prices', 'ignoring unfunded commitments and liquidity calls', 'comparing gross returns without fee and timing effects'],
    commandWords: ['recommend', 'evaluate', 'justify', 'determine', 'compare', 'explain'],
    formulas: ['Commitment pacing bridge', 'Net-of-fee return check', 'Private credit coverage screen', 'Exit multiple sensitivity', 'Infrastructure cash-flow stability', 'Limited partner liquidity reserve'],
    datasetRows: [
      { vehicle: 'buyout fund', commitment: 140, unfunded: '42%', fee: '2 and 20' },
      { vehicle: 'private credit', commitment: 95, unfunded: '18%', fee: '1 and 10' },
      { vehicle: 'infrastructure', commitment: 120, unfunded: '31%', fee: '1.25 and 15' },
    ],
  },
  {
    id: 'private-wealth-pathway',
    title: 'Private Wealth Pathway',
    examWeight: '30-35%',
    pathway: 'private-wealth',
    focus: 'private wealth business models, goals-based planning, taxes, estate transfer, concentrated risk, family dynamics, and insurance planning',
    caseFrames: ['A family office revises an ultra-high-net-worth client plan after liquidity, tax, and transfer goals change', 'An adviser evaluates a concentrated founder position while preserving spending and estate objectives'],
    decisions: ['recommend the goals-based wealth planning action', 'evaluate the tax or liquidity trade-off supported by the client facts', 'justify the estate transfer or risk mitigation strategy', 'determine which planning constraint controls the recommendation'],
    traps: ['solving only for expected return while ignoring spending policy', 'treating family preference as legally enforceable authority', 'recommending diversification without tax and control analysis'],
    commandWords: ['recommend', 'evaluate', 'justify', 'determine', 'identify', 'explain'],
    formulas: ['After-tax liquidity need', 'Concentrated position risk bridge', 'Goals-based funded ratio', 'Estate transfer sufficiency', 'Insurance coverage gap', 'Family governance decision path'],
    datasetRows: [
      { client: 'founder family', liquidityNeed: 'annual gifts', taxConstraint: 'low basis stock', transferGoal: 'control retained' },
      { client: 'global family office', liquidityNeed: 'quarterly spending', taxConstraint: 'multi-jurisdiction', transferGoal: 'education trust' },
      { client: 'retired executive', liquidityNeed: 'health reserve', taxConstraint: 'deferred comp', transferGoal: 'charitable bequest' },
    ],
  },
];
