import type { Level2TopicSpec } from './factory';

export const level2TopicSpecs: Level2TopicSpec[] = [
  {
    id: 'ethics',
    title: 'Ethics & Professional Standards',
    examWeight: '10-15%',
    focus: 'case-based professional judgment, duties, conflicts, and conduct analysis',
    caseFrames: ['A supervisor reviews client allocation notes after a conflict disclosure', 'An analyst prepares a recommendation after issuer management offers selective access'],
    decisions: ['evaluate the duty or standard controlling the case', 'select the professional conduct response supported by the facts', 'identify the disclosure or supervisory step required', 'separate loyal client service from preferential treatment'],
    traps: ['assuming firm approval cures an unsupported action', 'treating disclosure as a substitute for fair dealing', 'trading before resolving materiality and confidentiality'],
    formulas: ['Ethics case decision tree', 'Conflict disclosure sufficiency', 'Fair dealing allocation check', 'Supervisory response test'],
    datasetRows: [
      { case: 'allocation review', stakeholder: 'advisory clients', conflict: 'limited opportunity', evidence: 'documented policy' },
      { case: 'issuer meeting', stakeholder: 'research clients', conflict: 'selective access', evidence: 'reasonable basis file' },
      { case: 'performance claim', stakeholder: 'prospects', conflict: 'unsupported composite', evidence: 'corrected presentation' },
    ],
  },
  {
    id: 'quant-methods',
    title: 'Quantitative Methods',
    examWeight: '5-10%',
    focus: 'regression, time series, model diagnostics, and machine-learning interpretation',
    caseFrames: ['A research team reviews regression output for a factor model', 'A candidate evaluates whether a forecasting model is reliable out of sample'],
    decisions: ['interpret model output from the exhibit', 'diagnose a regression or time-series limitation', 'select the inference conclusion supported by the evidence', 'connect model fit to investment usefulness'],
    traps: ['reading statistical significance as economic importance', 'ignoring instability in the forecast period', 'treating correlation as a causal result'],
    formulas: ['Regression prediction error', 'Standard error interpretation', 'R-squared usefulness check', 'Out-of-sample validation score'],
    datasetRows: [
      { model: 'factor alpha', coefficient: '0.42', tStat: '2.3', sample: 'monthly returns' },
      { model: 'spread forecast', coefficient: '-0.18', tStat: '-1.1', sample: 'rolling quarters' },
      { model: 'volatility signal', coefficient: '0.64', tStat: '3.0', sample: 'daily data' },
    ],
  },
  {
    id: 'economics',
    title: 'Economics',
    examWeight: '5-10%',
    focus: 'currency, growth, regulation, and macro scenario analysis in item sets',
    caseFrames: ['A strategist reviews currency and inflation exhibits for a multi-country allocation', 'An analyst evaluates whether policy changes support growth expectations'],
    decisions: ['interpret the currency or parity implication', 'connect policy transmission to expected growth', 'identify the macro indicator that changes the forecast', 'separate nominal and real effects'],
    traps: ['quoting the exchange rate in the wrong direction', 'assuming policy intent equals realized output', 'mixing nominal growth with real purchasing power'],
    formulas: ['Interest rate parity signal', 'Real rate bridge', 'Currency quote direction', 'Growth decomposition check'],
    datasetRows: [
      { country: 'Asteria', inflation: '3.1%', policyRate: '4.4%', fxMove: 'currency up 2%' },
      { country: 'Boreal', inflation: '1.8%', policyRate: '2.2%', fxMove: 'currency down 1%' },
      { country: 'Cygnus', inflation: '5.0%', policyRate: '6.1%', fxMove: 'currency flat' },
    ],
  },
  {
    id: 'fsa',
    title: 'Financial Statement Analysis',
    examWeight: '10-15%',
    focus: 'intercorporate investments, pensions, multinationals, quality, and adjustments',
    caseFrames: ['An analyst adjusts statements for pension and lease comparability', 'A credit team evaluates earnings quality across multinational issuers'],
    decisions: ['select the reporting adjustment supported by the footnote', 'interpret quality of earnings from case evidence', 'connect accounting method to ratio comparability', 'identify the cash-flow implication of the adjustment'],
    traps: ['using reported earnings without reading the footnote', 'normalizing one ratio but leaving the linked account unchanged', 'treating translation effects as operating improvement'],
    formulas: ['Adjusted leverage bridge', 'Quality of earnings ratio', 'Pension adjustment signal', 'Currency translation effect'],
    datasetRows: [
      { issuer: 'Northstar', ebit: 124, debt: 410, pensionStatus: 'underfunded' },
      { issuer: 'Harbor', ebit: 98, debt: 360, pensionStatus: 'overfunded' },
      { issuer: 'Mesa', ebit: 76, debt: 290, pensionStatus: 'service cost rising' },
    ],
  },
  {
    id: 'corporate',
    title: 'Corporate Issuers',
    examWeight: '5-10%',
    focus: 'capital structure, governance, payout, and investment decision item sets',
    caseFrames: ['A board reviews capital allocation alternatives after leverage changes', 'A treasurer evaluates payout policy under a new funding plan'],
    decisions: ['interpret the capital structure implication', 'select the governance control that protects shareholders', 'connect payout policy to investment needs', 'evaluate the project decision from incremental cash flows'],
    traps: ['including sunk costs in the project case', 'treating cheaper debt as lower total risk', 'ignoring agency costs in governance analysis'],
    formulas: ['Incremental NPV bridge', 'Target leverage check', 'Payout sustainability signal', 'Governance risk screen'],
    datasetRows: [
      { project: 'capacity expansion', outlay: 240, irr: '9.8%', targetLeverage: '38%' },
      { project: 'automation', outlay: 120, irr: '11.4%', targetLeverage: '42%' },
      { project: 'buyback', outlay: 180, irr: 'n/a', targetLeverage: '47%' },
    ],
  },
  {
    id: 'equity',
    title: 'Equity Valuation',
    examWeight: '10-15%',
    focus: 'DCF, residual income, private company valuation, and multiples in cases',
    caseFrames: ['An analyst compares DCF and market multiple evidence for two issuers', 'A valuation committee reviews residual income assumptions after a margin change'],
    decisions: ['select the valuation model that fits the company facts', 'interpret a multiple after controlling for growth and risk', 'connect residual income to book value and required return', 'identify the private-company adjustment needed'],
    traps: ['using the lowest multiple without checking fundamentals', 'treating accounting earnings as free cash flow', 'ignoring control and marketability adjustments'],
    formulas: ['DCF value bridge', 'Residual income value', 'Justified multiple check', 'Private company discount screen'],
    datasetRows: [
      { company: 'Aster Foods', growth: '4.5%', margin: '12%', beta: 0.9 },
      { company: 'Beacon Software', growth: '12.0%', margin: '24%', beta: 1.3 },
      { company: 'Cobalt Utilities', growth: '2.8%', margin: '18%', beta: 0.7 },
    ],
  },
  {
    id: 'fixed-income',
    title: 'Fixed Income',
    examWeight: '10-15%',
    focus: 'term structure, credit, embedded options, structured products, and valuation interpretation',
    caseFrames: ['A portfolio manager reviews a curve shift and credit spread exhibit', 'An analyst evaluates an embedded-option bond after rates decline'],
    decisions: ['interpret curve and spread effects separately', 'select the valuation conclusion supported by duration and convexity', 'identify embedded-option risk in the case', 'connect securitized cash-flow assumptions to price sensitivity'],
    traps: ['mixing benchmark rate moves with issuer spread changes', 'using duration without checking convexity or option effects', 'assuming yield to maturity is a realized return'],
    formulas: ['Spread duration bridge', 'Option-adjusted spread signal', 'Key-rate duration check', 'Structured cash-flow sensitivity'],
    datasetRows: [
      { bond: 'Alpha 2030', spread: '84 bp', duration: 5.2, option: 'none' },
      { bond: 'Beta callable', spread: '126 bp', duration: 4.7, option: 'issuer call' },
      { bond: 'Mortgage pool', spread: '150 bp', duration: 3.6, option: 'prepayment' },
    ],
  },
  {
    id: 'derivatives',
    title: 'Derivatives',
    examWeight: '5-10%',
    focus: 'option valuation, swaps, forwards, futures, and risk-neutral case reasoning',
    caseFrames: ['A risk team evaluates option and futures hedges for a portfolio exposure', 'A treasury desk reviews swap cash flows after a rate move'],
    decisions: ['identify the derivative payoff direction', 'select the hedge that offsets the exposure', 'interpret no-arbitrage pricing from case inputs', 'connect option moneyness to exercise value'],
    traps: ['reversing long and short payoff direction', 'hedging in the same direction as the exposure', 'treating option premium as intrinsic value'],
    formulas: ['Forward value bridge', 'Option payoff check', 'Swap net payment', 'No-arbitrage carry signal'],
    datasetRows: [
      { contract: 'equity call', underlying: 54, strike: 50, position: 'long' },
      { contract: 'rate swap', underlying: 'rates rise', strike: 'pay fixed', position: 'payer' },
      { contract: 'currency forward', underlying: 1.18, strike: 1.15, position: 'long base' },
    ],
  },
  {
    id: 'alternatives',
    title: 'Alternative Investments',
    examWeight: '5-10%',
    focus: 'private equity, real estate, commodities, hedge funds, and valuation cases',
    caseFrames: ['A portfolio analyst compares private market and public market valuation evidence', 'A committee reviews fee, liquidity, and appraisal exhibits for an allocation'],
    decisions: ['identify the liquidity or valuation feature that changes the conclusion', 'interpret fee effects on investor return', 'connect alternative exposure to portfolio role', 'select the risk most supported by the case facts'],
    traps: ['treating appraisal value as a traded price', 'ignoring lockups and gates', 'subtracting performance fees from the wrong base'],
    formulas: ['Net return after fees', 'Appraisal lag signal', 'Liquidity haircut check', 'Portfolio role bridge'],
    datasetRows: [
      { vehicle: 'private equity', liquidity: 'locked', fee: '2 and 20', valuation: 'company marks' },
      { vehicle: 'core real estate', liquidity: 'quarterly', fee: '1.0%', valuation: 'income appraisal' },
      { vehicle: 'commodity index', liquidity: 'daily', fee: '0.35%', valuation: 'futures curve' },
    ],
  },
  {
    id: 'portfolio',
    title: 'Portfolio Management And Wealth Planning',
    examWeight: '10-15%',
    focus: 'factor models, active management, risk budgeting, and wealth planning cases',
    caseFrames: ['A portfolio committee reviews active risk, factor exposure, and client constraints', 'An adviser evaluates whether a wealth plan satisfies liquidity and time horizon needs'],
    decisions: ['interpret active risk or factor exposure from the exhibit', 'connect client constraints to portfolio construction', 'select the performance measure that fits the case', 'identify the rebalancing or risk-budget action supported by facts'],
    traps: ['treating active return as risk-adjusted performance', 'ignoring liquidity needs in allocation advice', 'averaging risks without using correlation'],
    formulas: ['Information ratio bridge', 'Active risk budget', 'Constraint-aware allocation', 'Factor exposure check'],
    datasetRows: [
      { portfolio: 'Core active', activeReturn: '1.2%', trackingError: '3.8%', constraint: 'moderate liquidity' },
      { portfolio: 'Income client', activeReturn: '0.4%', trackingError: '1.6%', constraint: 'annual withdrawals' },
      { portfolio: 'Growth client', activeReturn: '2.1%', trackingError: '5.2%', constraint: 'long horizon' },
    ],
  },
];
